FROM ubuntu:18.04
MAINTAINER sumitasok@gmail.com

RUN apt-get update
RUN apt-get upgrade

RUN apt-get install -y build-essential cmake pkg-config

# https://askubuntu.com/questions/593433/error-sudo-add-apt-repository-command-not-found
RUN apt-get install -y software-properties-common
# https://stackoverflow.com/questions/43484357/opencv-in-ubuntu-17-04/44488374#44488374
RUN add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
RUN apt update
RUN apt install -y libjasper1 libjasper-dev
RUN apt-get install -y libjpeg8-dev libtiff5-dev libjasper-dev libpng-dev
RUN apt-get install -y libgtk2.0-dev libgtk-3-dev
RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
RUN apt-get install -y libatlas-base-dev gfortran
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y wget
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install virtualenv virtualenvwrapper
RUN rm -rf ~/.cache/pip

ENV WORKON_HOME=$HOME/.virtualenvs
# RUN usermod -s /bin/bash root
# https://stackoverflow.com/questions/20635472/using-the-run-instruction-in-a-dockerfile-with-source-does-not-work
RUN /bin/bash -c "source /usr/local/bin/virtualenvwrapper.sh"
# RUN /bin/bash "source /.bashrc"
# RUN dpkg-reconfigure bash
# https://superuser.com/questions/715722/how-to-do-dpkg-reconfigure-dash-as-bash-automatically
# RUN echo "dash dash/sh boolean false" | debconf-set-selections
# RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure bash
ADD --chown=root:root virtualenv.sh /
RUN ["./virtualenv.sh"]
RUN apt-get install -y python2.7-dev
RUN pip install numpy
RUN pip install scipy matplotlib
RUN pip install scikit-learn
RUN pip install -U scikit-image
RUN pip install mahotas imutils Pillow commentjson

RUN wget -O opencv-2.4.10.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.10/opencv-2.4.10.zip/download
RUN apt-get install -y unzip
RUN unzip opencv-2.4.10.zip
RUN cd opencv-2.4.10

RUN mkdir build
RUN cd build
ADD --chown=root:root cmake.sh /
RUN ["./cmake.sh"]

RUN make -j4

RUN make install
RUN ldconfig
